# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "discount-remix"
client_id = "5a8f064bf48edda334af03c2444d1196"
application_url = "https://gamma-rm-admitted-villas.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_discounts,read_themes,write_orders,read_inventory,read_gift_cards,read_locations,read_markets"

[auth]
redirect_urls = [
  "https://gamma-rm-admitted-villas.trycloudflare.com/auth/callback",
  "https://gamma-rm-admitted-villas.trycloudflare.com/auth/shopify/callback",
  "https://gamma-rm-admitted-villas.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "pritam-test-store-440.myshopify.com"
